import type { User, Entreprise, Formalite, Cabinet } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    nom: "Hacene",
    prenom: "Laëtitia",
    email: "contact@urgencesformalites.fr",
    telephone: "06 12 34 56 78",
    identifiant: "l.hacene",
    password: "UrgForm@paris75!!",
    role: "admin",
  },
  {
    id: "2",
    nom: "Hacene",
    prenom: "Ahmed",
    email: "quixline@gmail.com",
    telephone: "06 98 76 54 32",
    identifiant: "a.hacene",
    password: "admin",
    role: "admin",
  },
  {
    id: "3",
    nom: "Martin",
    prenom: "Sophie",
    email: "sophie.martin@urgencesformalites.fr",
    telephone: "06 11 22 33 44",
    identifiant: "s.martin",
    password: "admin",
    role: "formaliste",
  },
  {
    id: "4",
    nom: "Durand",
    prenom: "Julien",
    email: "julien.durand@urgencesformalites.fr",
    telephone: "06 55 66 77 88",
    identifiant: "j.durand",
    password: "admin",
    role: "formaliste",
  },
];

export const mockCabinets: Cabinet[] = [
  {
    id: "cab-1",
    nom: "Cabinet Moreau & Associés",
    telephone: "01 42 60 10 20",
    email: "contact@moreau-associes.fr",
  },
  {
    id: "cab-2",
    nom: "Cabinet Lefèvre",
    telephone: "01 45 78 33 00",
    email: "info@cabinet-lefevre.fr",
  },
  {
    id: "cab-3",
    nom: "Comptabilité Petit",
    telephone: "04 72 10 55 80",
    email: "comptabilite@petit-lyon.fr",
  },
  {
    id: "cab-4",
    nom: "Cabinet Dubois Conseil",
    telephone: "01 53 40 22 10",
    email: "conseil@dubois-conseil.fr",
  },
  {
    id: "cab-5",
    nom: "Cabinet Laurent Juridique",
    telephone: "01 47 20 88 15",
    email: "juridique@laurent-avocats.fr",
  },
];

export const mockEntreprises: Entreprise[] = [
  {
    id: "e1",
    denomination: "Tech Solutions SAS",
    siren: "123 456 789",
    formeJuridique: "SAS",
    siegeSocial: "15 Rue de la Paix, 75002 Paris",
    capital: 50000,
    dirigeant: "Jean Moreau",
    dateCreation: "2023-03-15",
  },
  {
    id: "e2",
    denomination: "Immobilière du Centre SCI",
    siren: "987 654 321",
    formeJuridique: "SCI",
    siegeSocial: "8 Avenue des Champs-Élysées, 75008 Paris",
    capital: 100000,
    dirigeant: "Marie Lefèvre",
    dateCreation: "2020-06-01",
  },
  {
    id: "e3",
    denomination: "Boulangerie Petit SARL",
    siren: "456 789 123",
    formeJuridique: "SARL",
    siegeSocial: "3 Place du Marché, 69001 Lyon",
    capital: 15000,
    dirigeant: "Pierre Petit",
    dateCreation: "2019-01-10",
  },
  {
    id: "e4",
    denomination: "Conseil & Stratégie SASU",
    siren: "321 654 987",
    formeJuridique: "SASU",
    siegeSocial: "22 Boulevard Haussmann, 75009 Paris",
    capital: 10000,
    dirigeant: "Claire Dubois",
    dateCreation: "2024-01-20",
  },
  {
    id: "e5",
    denomination: "Restaurant Le Gourmet EURL",
    siren: "654 321 987",
    formeJuridique: "EURL",
    siegeSocial: "5 Rue de Rivoli, 75001 Paris",
    capital: 8000,
    dirigeant: "François Laurent",
    dateCreation: "2021-09-12",
  },
];

export const mockFormalites: Formalite[] = [
  {
    id: "f1",
    reference: "UF-2026-001",
    type: "immatriculation",
    statut: "valide",
    entrepriseId: "e1",
    entrepriseDenomination: "Tech Solutions SAS",
    cabinet: "Cabinet Moreau & Associés",
    description: "Immatriculation SAS au RCS de Paris",
    dateCreation: "2026-01-10",
    dateSoumission: "2026-01-12",
    dateValidation: "2026-01-20",
    formaliste: "Ahmed Hacene",
    refINPI: "INPI-2026-78452",
  },
  {
    id: "f2",
    reference: "UF-2026-002",
    type: "modification",
    statut: "en-traitement",
    entrepriseId: "e2",
    entrepriseDenomination: "Immobilière du Centre SCI",
    cabinet: "Cabinet Lefèvre",
    description: "Transfert de siège social — nouvelle adresse",
    dateCreation: "2026-02-05",
    dateSoumission: "2026-02-07",
    formaliste: "Laëtitia Hacene",
    refINPI: "INPI-2026-81203",
  },
  {
    id: "f3",
    reference: "UF-2026-003",
    type: "depot-comptes",
    statut: "en-traitement",
    entrepriseId: "e3",
    entrepriseDenomination: "Boulangerie Petit SARL",
    cabinet: "Comptabilité Petit",
    description: "Dépôt des comptes annuels exercice 2025",
    dateCreation: "2026-02-20",
    dateSoumission: "2026-02-22",
    formaliste: "Ahmed Hacene",
    refINPI: "INPI-2026-83401",
  },
  {
    id: "f4",
    reference: "UF-2026-004",
    type: "cession",
    statut: "brouillon",
    entrepriseId: "e2",
    entrepriseDenomination: "Immobilière du Centre SCI",
    cabinet: "Cabinet Lefèvre",
    description: "Cession de parts sociales — 30% du capital",
    dateCreation: "2026-03-01",
    formaliste: "Laëtitia Hacene",
  },
  {
    id: "f5",
    reference: "UF-2026-005",
    type: "radiation",
    statut: "rejete",
    entrepriseId: "e5",
    entrepriseDenomination: "Restaurant Le Gourmet EURL",
    cabinet: "Cabinet Laurent Juridique",
    description: "Radiation suite dissolution anticipée",
    dateCreation: "2026-02-15",
    dateSoumission: "2026-02-18",
    formaliste: "Ahmed Hacene",
    refINPI: "INPI-2026-80115",
    observations: "Pièces justificatives manquantes — PV d'AG requis",
  },
  {
    id: "f6",
    reference: "UF-2026-006",
    type: "beneficiaires-effectifs",
    statut: "en-traitement",
    entrepriseId: "e4",
    entrepriseDenomination: "Conseil & Stratégie SASU",
    cabinet: "Cabinet Dubois Conseil",
    description: "Déclaration initiale des bénéficiaires effectifs",
    dateCreation: "2026-03-03",
    dateSoumission: "2026-03-04",
    formaliste: "Laëtitia Hacene",
    refINPI: "INPI-2026-84920",
  },
  {
    id: "f7",
    reference: "UF-2026-007",
    type: "modification",
    statut: "en-traitement",
    entrepriseId: "e1",
    entrepriseDenomination: "Tech Solutions SAS",
    cabinet: "Cabinet Moreau & Associés",
    description: "Changement de dirigeant — nomination nouveau président",
    dateCreation: "2026-03-05",
    dateSoumission: "2026-03-06",
    formaliste: "Ahmed Hacene",
    refINPI: "INPI-2026-85102",
  },
  {
    id: "f8",
    reference: "UF-2026-008",
    type: "immatriculation",
    statut: "brouillon",
    entrepriseId: "e4",
    entrepriseDenomination: "Conseil & Stratégie SASU",
    cabinet: "Cabinet Dubois Conseil",
    description: "Création d'une filiale — immatriculation SASU",
    dateCreation: "2026-03-06",
    formaliste: "Laëtitia Hacene",
  },
];
